@extends('layouts.customer')
@section('title', 'Payment History | Smart Basket')
@section('page_title', 'Payment History')
@push('styles')
<style>
.payment-page{padding:28px;max-width:1400px;margin:auto}.payment-hero,.payment-card{background:var(--sb-surface,#fff);border:1px solid var(--sb-border,rgba(15,23,42,.1));border-radius:22px;box-shadow:0 16px 45px rgba(15,23,42,.08)}.payment-hero{padding:28px;margin-bottom:20px;background:linear-gradient(135deg,rgba(37,99,235,.13),rgba(124,58,237,.09)),var(--sb-surface,#fff)}.payment-hero h1{margin:0;color:var(--sb-text,#172033);font-size:clamp(1.5rem,3vw,2rem);font-weight:800}.payment-hero p{color:var(--sb-muted,#64748b)}.payment-filter{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:12px;padding:18px;margin-bottom:20px}.payment-filter input,.payment-filter select{min-height:44px;border:1px solid var(--sb-border,rgba(15,23,42,.14));border-radius:11px;padding:0 12px;background:var(--sb-input,var(--sb-surface,#fff));color:var(--sb-text,#172033)}.payment-filter button,.payment-action{border:0;border-radius:11px;padding:0 17px;min-height:44px;background:#2563eb;color:white;font-weight:700;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:7px}.payment-list{overflow:hidden}.payment-table{width:100%;border-collapse:collapse}.payment-table td{padding:16px;text-align:left;border-bottom:1px solid var(--sb-border,rgba(15,23,42,.09));color:var(--sb-text,#172033);vertical-align:middle}.payment-table small{color:var(--sb-muted,#64748b);word-break:break-word}.payment-badge{display:inline-flex;padding:5px 9px;border-radius:99px;font-size:.75rem;font-weight:800;text-transform:capitalize;background:rgba(245,158,11,.14);color:#b45309}.payment-badge.paid{background:rgba(22,163,74,.14);color:#15803d}.payment-badge.failed,.payment-badge.cancelled{background:rgba(220,38,38,.14);color:#b91c1c}.payment-badge.refunded{background:rgba(124,58,237,.14);color:#6d28d9}.empty-payments{text-align:center;padding:64px 20px;color:var(--sb-muted,#64748b)}@media(max-width:850px){.payment-page{padding:16px}.payment-filter{grid-template-columns:1fr 1fr}.payment-filter input{grid-column:1/-1}.payment-table,.payment-table tbody,.payment-table tr,.payment-table td{display:block;width:100%}.payment-table tr{padding:12px;border-bottom:1px solid var(--sb-border,rgba(15,23,42,.1))}.payment-table td{padding:5px 4px;border:0}.payment-table td:before{content:attr(data-label);display:inline-block;width:42%;font-size:.72rem;text-transform:uppercase;color:var(--sb-muted,#64748b);font-weight:700}.payment-table td:last-child{margin-top:8px}.payment-action{width:100%}}
</style>
@endpush
@section('content')
<main class="payment-page"><section class="payment-hero"><h1><i class="fa-solid fa-wallet me-2"></i>Your payment history</h1><p class="mb-0 mt-2">Review secure payment records for your Smart Basket orders.</p></section>
<form class="payment-filter payment-card" method="GET"><input name="search" value="{{ request('search') }}" placeholder="Search payment, order, or transaction ID"><select name="status"><option value="">All statuses</option>@foreach(['pending','processing','paid','failed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><input type="date" name="date" value="{{ request('date') }}" aria-label="Payment date"><button type="submit"><i class="fa-solid fa-filter"></i>Filter</button></form>
<section class="payment-card payment-list">@forelse($payments as $payment)@php($refundStatus = $payment->refunds->sortByDesc('created_at')->first()?->status)<table class="payment-table"><tbody><tr><td data-label="Payment"><strong>#{{ $payment->id }}</strong><small class="d-block">{{ $payment->gateway_payment_id ?: 'Gateway reference pending' }}</small></td><td data-label="Order"><strong>{{ collect($payment->order_ids ?? [])->map(fn($id) => 'SB-'.$id)->implode(', ') ?: 'Not confirmed yet' }}</strong></td><td data-label="Amount"><strong>{{ $payment->currency }} {{ number_format((float) $payment->amount, 2) }}</strong></td><td data-label="Method"><span class="text-capitalize">{{ $payment->payment_method }}</span><small class="d-block">{{ ucfirst($payment->gateway) }}</small></td><td data-label="Status"><span class="payment-badge {{ $payment->status }}">{{ $payment->status }}</span></td><td data-label="Transaction"><small>{{ $payment->gateway_transaction_id ?: $payment->gateway_payment_id ?: '—' }}</small></td><td data-label="Date"><small>{{ $payment->created_at?->format('d M Y, h:i A') }}</small></td><td data-label="Refund"><span class="payment-badge {{ $refundStatus === 'refunded' ? 'refunded' : '' }}">{{ $refundStatus ? ucfirst($refundStatus) : 'Not requested' }}</span></td><td data-label=""><a class="payment-action" href="{{ route('payments.show', $payment) }}">View details</a></td></tr></tbody></table>@empty<div class="empty-payments"><i class="fa-regular fa-credit-card fa-2x mb-3"></i><h3>No payment records found</h3><p class="mb-0">Payments for your account will appear here.</p></div>@endforelse</section><div class="mt-4">{{ $payments->links() }}</div></main>
@endsection
