@extends('layouts.customer')
@section('title', 'Payment Receipt | Smart Basket')
@section('page_title', 'Payment Receipt')
@push('styles')
<style>
.receipt-page{max-width:900px;padding:28px;margin:auto}.receipt{background:var(--sb-surface,#fff);border:1px solid var(--sb-border,rgba(15,23,42,.1));border-radius:22px;overflow:hidden;box-shadow:0 18px 55px rgba(15,23,42,.1)}.receipt-header{padding:28px;background:linear-gradient(135deg,#172554,#2563eb);color:#fff;display:flex;justify-content:space-between;gap:16px}.receipt-header h1{font-size:1.7rem;margin:0;font-weight:800}.receipt-body{padding:28px}.receipt-section{margin-bottom:25px}.receipt-section h2{font-size:.78rem;color:var(--sb-muted,#64748b);letter-spacing:.09em;text-transform:uppercase;margin:0 0 10px}.receipt-grid{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--sb-border,rgba(15,23,42,.1));border:1px solid var(--sb-border,rgba(15,23,42,.1));border-radius:12px;overflow:hidden}.receipt-grid div{padding:13px;background:var(--sb-surface,#fff);color:var(--sb-text,#172033)}.receipt-grid span{display:block;font-size:.75rem;color:var(--sb-muted,#64748b);margin-bottom:4px}.total{font-size:1.3rem;font-weight:800;color:#2563eb}.print-actions{display:flex;gap:10px;margin-bottom:15px}.print-actions a,.print-actions button{border:1px solid var(--sb-border,rgba(15,23,42,.15));border-radius:10px;padding:9px 12px;background:var(--sb-surface,#fff);color:var(--sb-text,#172033);text-decoration:none;font-weight:700}@media(max-width:600px){.receipt-page{padding:16px}.receipt-header,.receipt-grid{display:block}.receipt-grid div{border-bottom:1px solid var(--sb-border,rgba(15,23,42,.1))}}@media print{.sb-sidebar,.sb-topbar,.print-actions{display:none!important}.sb-main{margin:0!important}.receipt-page{padding:0}.receipt{box-shadow:none;border:0}}
</style>
@endpush
@section('content')
@php($refund = $payment->refunds()->latest()->first())
<main class="receipt-page"><div class="print-actions"><a href="{{ route('payments.show', $payment) }}">Back to payment</a><button type="button" onclick="window.print()"><i class="fa-solid fa-print me-1"></i>Print receipt</button></div><article class="receipt"><header class="receipt-header"><div><h1>SMART BASKET</h1><div>Payment receipt</div></div><div><strong>Payment #{{ $payment->id }}</strong><br><small>Issued {{ now()->format('d M Y, h:i A') }}</small></div></header><div class="receipt-body">
<section class="receipt-section"><h2>Customer information</h2><div class="receipt-grid"><div><span>Name</span>{{ auth()->user()->name }}</div><div><span>Email</span>{{ auth()->user()->email }}</div></div></section>
<section class="receipt-section"><h2>Payment information</h2><div class="receipt-grid"><div><span>Payment ID</span>#{{ $payment->id }}</div><div><span>Transaction ID</span>{{ $payment->gateway_transaction_id ?: $payment->gateway_payment_id ?: 'Not available' }}</div><div><span>Payment method</span>{{ $payment->payment_method }}</div><div><span>Gateway</span>{{ ucfirst($payment->gateway) }}</div><div><span>Payment status</span>{{ ucfirst($payment->status) }}</div><div><span>Payment date/time</span>{{ ($payment->completed_at ?? $payment->verified_at ?? $payment->created_at)?->format('d M Y, h:i A') }}</div><div><span>Refund status</span>{{ $refund ? ucfirst($refund->status) : 'Not requested' }}</div><div><span>Amount</span><strong class="total">{{ $payment->currency }} {{ number_format((float) $payment->amount, 2) }}</strong></div></div></section>
<section class="receipt-section"><h2>Order and seller information</h2>@forelse($orders as $order)<div class="receipt-grid mb-2"><div><span>Order ID</span>SB-{{ $order->id }}</div><div><span>Order date</span>{{ $order->created_at?->format('d M Y, h:i A') }}</div><div><span>Seller</span>{{ $order->seller?->shop_name ?: $order->seller?->seller_name ?: 'Smart Basket seller' }}</div><div><span>Order status</span>{{ $order->order_status ?: $order->status ?: 'Placed' }}</div></div>@empty<div class="text-muted">No confirmed order is attached to this payment yet.</div>@endforelse</section>
<p class="text-muted small mb-0">This receipt contains no card, bank, UPI, or gateway credentials.</p></div></article></main>
@endsection
