@extends('layouts.customer')
@section('title', 'Payment Details | Smart Basket')
@section('page_title', 'Payment Details')
@push('styles')
<style>
.payment-detail{max-width:1050px;margin:auto;padding:28px}.detail-card{background:var(--sb-surface,#fff);border:1px solid var(--sb-border,rgba(15,23,42,.1));border-radius:22px;padding:25px;box-shadow:0 16px 45px rgba(15,23,42,.08)}.detail-head{display:flex;justify-content:space-between;gap:16px;align-items:start;margin-bottom:20px}.detail-head h1{color:var(--sb-text,#172033);margin:0;font-size:clamp(1.4rem,3vw,2rem);font-weight:800}.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:var(--sb-border,rgba(15,23,42,.1));border:1px solid var(--sb-border,rgba(15,23,42,.1));border-radius:15px;overflow:hidden}.detail-grid div{background:var(--sb-surface,#fff);padding:15px}.detail-grid span{display:block;color:var(--sb-muted,#64748b);font-size:.75rem;text-transform:uppercase;letter-spacing:.05em;margin-bottom:5px}.detail-grid strong{color:var(--sb-text,#172033);overflow-wrap:anywhere}.status{padding:7px 11px;border-radius:99px;font-weight:800;background:rgba(245,158,11,.14);color:#b45309}.status.paid{background:rgba(22,163,74,.14);color:#15803d}.status.failed,.status.cancelled{background:rgba(220,38,38,.14);color:#b91c1c}.notice{margin:18px 0;padding:14px;border-radius:12px;background:rgba(220,38,38,.1);color:#b91c1c}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.button{border:0;border-radius:11px;padding:12px 16px;background:#2563eb;color:white;font-weight:750;text-decoration:none}.button.secondary{background:transparent;border:1px solid var(--sb-border,rgba(15,23,42,.18));color:var(--sb-text,#172033)}@media(max-width:650px){.payment-detail{padding:16px}.detail-head{display:block}.detail-head .status{display:inline-block;margin-top:10px}.detail-grid{grid-template-columns:1fr}.actions>*{width:100%;text-align:center}}
</style>
@endpush
@section('content')
@php($refund = $payment->refunds()->latest()->first())
<main class="payment-detail"><section class="detail-card"><div class="detail-head"><div><h1><i class="fa-solid fa-receipt me-2"></i>Payment #{{ $payment->id }}</h1><p class="text-muted mb-0 mt-2">Secure transaction details for your Smart Basket order.</p></div><span class="status {{ $payment->status }}">{{ ucfirst($payment->status) }}</span></div>
@if(session('error'))<div class="notice">{{ session('error') }}</div>@endif
<div class="detail-grid"><div><span>Order ID</span><strong>{{ collect($payment->order_ids ?? [])->map(fn($id) => 'SB-'.$id)->implode(', ') ?: 'Order pending confirmation' }}</strong></div><div><span>Payment ID</span><strong>#{{ $payment->id }}</strong></div><div><span>Amount</span><strong>{{ $payment->currency }} {{ number_format((float) $payment->amount, 2) }}</strong></div><div><span>Payment method</span><strong>{{ $payment->payment_method }}</strong></div><div><span>Gateway</span><strong>{{ ucfirst($payment->gateway) }}</strong></div><div><span>Payment status</span><strong>{{ ucfirst($payment->status) }}</strong></div><div><span>Transaction ID</span><strong>{{ $payment->gateway_transaction_id ?: $payment->gateway_payment_id ?: 'Not available' }}</strong></div><div><span>Payment date</span><strong>{{ ($payment->completed_at ?? $payment->verified_at ?? $payment->created_at)?->format('d M Y, h:i A') }}</strong></div><div><span>Refund status</span><strong>{{ $refund ? ucfirst($refund->status) : 'Not requested' }}</strong></div><div><span>Gateway order reference</span><strong>{{ $payment->gateway_order_id ?: 'Not available' }}</strong></div></div>
@if($payment->failure_reason)<div class="notice"><strong>Failure reason:</strong> {{ $payment->failure_reason }}</div>@endif
<div class="actions"><a class="button secondary" href="{{ route('payments.index') }}">Back to history</a><a class="button secondary" href="{{ route('payments.receipt', $payment) }}">View receipt</a>@if(in_array($payment->status, ['failed','cancelled'], true) && empty($payment->order_ids))<form method="POST" action="{{ route('payments.retry', $payment) }}">@csrf<button class="button" type="submit"><i class="fa-solid fa-rotate-right me-1"></i>Retry Payment</button></form>@endif</div></section></main>
@endsection
