@extends('layouts.customer')

@section('content')
<div class="container py-5" style="max-width:900px">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">Delivery addresses</h1><p class="text-muted mb-0">Manage the addresses available at checkout.</p></div><a class="btn btn-outline-primary" href="{{ route('profile') }}">Profile</a></div>
    @if(session('success')) <div class="alert alert-success">{{ session('success') }}</div> @endif
    @if($errors->any()) <div class="alert alert-danger">{{ $errors->first() }}</div> @endif
    <div class="row g-3 mb-4">@forelse($addresses as $address)<div class="col-md-6"><div class="card h-100 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between"><strong>{{ $address->label }}</strong>@if($address->is_default)<span class="badge text-bg-primary">Default</span>@endif</div><p class="mb-1 mt-3">{{ $address->recipient_name }} · {{ $address->phone }}</p><p class="text-muted mb-3">{{ $address->address_line }}, {{ $address->city }}, {{ $address->state }} {{ $address->pincode }}</p><div class="d-flex gap-2"><form method="POST" action="{{ route('addresses.default', $address) }}">@csrf<button class="btn btn-sm btn-outline-primary" @disabled($address->is_default)>Set default</button></form><form method="POST" action="{{ route('addresses.destroy', $address) }}" onsubmit="return confirm('Remove this address?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove</button></form></div></div></div></div>@empty <p class="text-muted">No saved addresses yet.</p>@endforelse</div>
    <div class="card shadow-sm"><div class="card-body"><h2 class="h5 mb-3">Add address</h2><form method="POST" action="{{ route('addresses.store') }}">@csrf<div class="row g-3"><div class="col-md-4"><input class="form-control" name="label" value="{{ old('label','Home') }}" required placeholder="Label"></div><div class="col-md-8"><input class="form-control" name="recipient_name" value="{{ old('recipient_name', auth()->user()->name) }}" required placeholder="Recipient name"></div><div class="col-md-6"><input class="form-control" name="phone" value="{{ old('phone', auth()->user()->phone) }}" required placeholder="Phone"></div><div class="col-md-6"><input class="form-control" name="pincode" value="{{ old('pincode') }}" required placeholder="Pincode"></div><div class="col-12"><textarea class="form-control" name="address_line" required placeholder="Address">{{ old('address_line') }}</textarea></div><div class="col-md-4"><input class="form-control" name="city" required value="{{ old('city') }}" placeholder="City"></div><div class="col-md-4"><input class="form-control" name="state" required value="{{ old('state') }}" placeholder="State"></div><div class="col-md-4"><input class="form-control" name="country" required value="{{ old('country','India') }}" placeholder="Country"></div><div class="col-12"><button class="btn btn-primary">Save address</button></div></div></form></div></div>
</div>
@endsection
